config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root :to => 'users#index'


   resources :users do
     resources :images do
       resources :tags
     end
   end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :tags
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :images
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  def after_sign_in_path_for(resource)
    root_path
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    @user = current_user
    @image = Image.find(params[:id])
    @tags = @image.tags
  end

  def edit
    @image = Image.find(params[:id])

  end

  def index
    @user = current_user

  end

  def create
    @user = current_user
    @image = @user.images.create(image_params)
    redirect_to '/'
  end

  def update
     @image = Image.find(params[:id])
     if @image.update(image_params)
       redirect_to  user_image_path, notice: 'Product successfully updated!'
     else
       render :edit
     end
   end

 def destroy
   @user = current_user
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to root_path, notice: 'Product successfully deleted!'
  end

  def new
    @image = Image.new
    @user = current_user
  end

end

private
def user_params
  params.require(:user).permit(:name)
end

  def image_params
    params.require(:image).permit(:description, :image, :user_id, current_user)
  end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

before_action :authenticate_user!, :only => [:index]

  def show
  end

  def edit
  end

  def index
  end

  def new
    @tag = Tag.new
    @user = current_user
    @image = Image.find(params[:image_id])
  end

  def create
    @user = current_user
    @image = @user.images.find(params[:image_id])
    @tag = @image.tags.create(tag_params)
    redirect_to '/'
  end


end

private
  def tag_params
    params.require(:tag).permit(:name)
  end

def image_params
  params.require(:image).permit(:description, :image, :user_id, current_user)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :only => [:new, :edit] do
     redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def show
  end

  def edit
  end

  def index
    @user = current_user
    @images = @user.images
  end

  def new
  end

end

private
  def user_params
    params.require(:user).permit(:name)
end

def image_params
  params.require(:image).permit(:description, :image, :user_id, current_user)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for @image, url: user_images_path, html: { multipart: true } do |f| %>
<%= f.file_field :image %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<%= form_for @image, url: user_image_path, html: { multipart: true } do |f| %>
<%= f.file_field :image %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/images/index.html.erb
<h1>Images</h1>
<p>Find me in app/views/images/index.html.erb</p>

<%= link_to 'Delete', user_image_path(@user, @image), :method => :delete %>

app/views/images/new.html.erb
<h1>Images#new</h1>
<%= render 'form' %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<%= image_tag @image.image.url %>
<br>
<%= @image.description %>

<% @tags.each do |tag| %>
  <%= tag.name %>
<% end %>
<br>

<%= link_to 'Edit', edit_user_image_path(@user, @image) %>
<br>
<%= link_to 'Delete', user_image_path(@user, @image), :method => :delete %>
<br>
<%= link_to 'Add Tags', new_user_image_tag_path(@user, @image) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if current_user %>
       <%= current_user.email %> | <%= link_to "Sign out", '/users/sign_out', :method => :delete %>
     <% else %>
       <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
     <% end %>

     <%= flash[:alert] %>
     <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_for @tag, url: user_image_tags_path, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<%= render 'form' %>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Welcome, <%= @user.email %></h1>

<h3>Here are all your photos!</h3>

<% @images.each do |image| %>
  <%= image_tag image.image.url %>
  <p><%=link_to image.description, user_image_path(@user, image) %></p>


<% end %>

<%= link_to 'Add new image', new_user_image_path(@user) %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>